# Generated by Django 3.2.8 on 2021-10-08 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_data_type', models.CharField(choices=[('int_type', 'Int'), ('str_type', 'Str'), ('bool_type', 'Bool'), ('float_type', 'Float'), ('date_type', 'Date'), ('datetime_type', 'Datetime')], max_length=100)),
                ('to_data_type', models.CharField(choices=[('int_type', 'Int'), ('str_type', 'Str'), ('bool_type', 'Bool'), ('float_type', 'Float'), ('date_type', 'Date'), ('datetime_type', 'Datetime')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_toll', models.BooleanField(default=False)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DataSet',
                'verbose_name_plural': 'DataSets',
            },
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filed_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('data_type', models.CharField(choices=[('int_type', 'Int'), ('str_type', 'Str'), ('bool_type', 'Bool'), ('float_type', 'Float'), ('date_type', 'Date'), ('datetime_type', 'Datetime')], max_length=100)),
                ('data_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_data', to='core.dataset')),
            ],
        ),
    ]
