# Generated by Django 3.2.8 on 2021-10-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversion',
            options={'verbose_name': 'Conversion', 'verbose_name_plural': 'Conversion'},
        ),
        migrations.AlterModelOptions(
            name='metadata',
            options={'verbose_name': 'MetaData', 'verbose_name_plural': 'MetaData'},
        ),
        migrations.AddField(
            model_name='conversion',
            name='name',
            field=models.CharField(default='name', max_length=300),
            preserve_default=False,
        ),
    ]
