# Generated by Django 3.2.8 on 2021-10-08 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211008_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadata',
            old_name='filed_name',
            new_name='field_name',
        ),
    ]
