# Generated by Django 3.2.8 on 2021-10-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='json_field',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
